import { AIModelOption } from '../types/ai';

export const AVAILABLE_AI_MODELS: AIModelOption[] = [
  // 1. Local AI Models (Ollama, LM Studio, LocalAI, vLLM - 100% Free & Offline)
  {
    id: 'qwen:14b',
    name: 'Local AI — Qwen 14B (Ollama: qwen:14b)',
    provider: 'local',
    description: 'High-capability 14B parameter model for detailed resume structuring and synthesis.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'qwen2.5:14b',
    name: 'Local AI — Qwen 2.5 (14B)',
    provider: 'local',
    description: 'High-capability instruction-following and structured Markdown generation.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'qwen:7b',
    name: 'Local AI — Qwen 7B (Ollama: qwen:7b)',
    provider: 'local',
    description: 'Fast 7B model for quick keyword extraction and editing.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'qwen2.5:7b',
    name: 'Local AI — Qwen 2.5 (7B)',
    provider: 'local',
    description: 'Lightweight, fast instruction-following and ATS keyword synthesis.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'deepseek-r1:14b',
    name: 'Local AI — DeepSeek R1 Distill (14B)',
    provider: 'local',
    description: 'Deep local reasoning model for thorough ATS keyword extraction and metric validation.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'deepseek-r1:8b',
    name: 'Local AI — DeepSeek R1 Distill (8B)',
    provider: 'local',
    description: 'Fast local reasoning model for rigorous ATS keyword extraction.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'deepseek-r1:7b',
    name: 'Local AI — DeepSeek R1 Distill (7B)',
    provider: 'local',
    description: 'Ultra-lightweight local reasoning model.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'llama3.2',
    name: 'Local AI — Llama 3.2 (3B)',
    provider: 'local',
    description: 'Runs completely locally on your hardware. Fast, 100% private, and zero API costs.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'llama3.1:8b',
    name: 'Local AI — Llama 3.1 (8B)',
    provider: 'local',
    description: 'Balanced performance, high stability and reasoning for local execution.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'mistral:7b',
    name: 'Local AI — Mistral (7B)',
    provider: 'local',
    description: 'High-quality local executive writing and concise achievement framing.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'phi4:14b',
    name: 'Local AI — Microsoft Phi-4 (14B)',
    provider: 'local',
    description: 'State-of-the-art small language model with high logical reasoning accuracy.',
    isFree: true,
    requiresKey: false,
  },
  {
    id: 'custom-local-model',
    name: 'Local AI — Custom Model Tag...',
    provider: 'local',
    description: 'Connect to any custom model loaded in your Ollama or LM Studio instance.',
    isFree: true,
    requiresKey: false,
  },

  // 2. Google Gemini (Cloud - Free API Key from Google AI Studio)
  {
    id: 'gemini-3.5-flash-lite',
    name: 'Google Gemini 3.5 Flash Lite (Recommended — 500 Req/Day)',
    provider: 'gemini',
    description: 'High free tier quota (500 requests/day, 15 RPM). Fast and reliable ATS synthesis.',
    isFree: false,
    requiresKey: true,
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Google Gemini 2.5 Flash (High Speed)',
    provider: 'gemini',
    description: 'Ultra-fast synthesis with high accuracy and reliable free tier quotas.',
    isFree: false,
    requiresKey: true,
  },
  {
    id: 'gemini-3.1-flash-lite',
    name: 'Google Gemini 3.1 Flash Lite (500 Req/Day)',
    provider: 'gemini',
    description: 'Large daily capacity quota (500 requests/day) for high volume CV crafting.',
    isFree: false,
    requiresKey: true,
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Google Gemini 2.5 Pro (Deep Reasoning)',
    provider: 'gemini',
    description: 'Top-tier complex analysis and executive resume crafting.',
    isFree: false,
    requiresKey: true,
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Google Gemini 2.0 Flash (Stable)',
    provider: 'gemini',
    description: 'Highly stable multimodal model with exceptional throughput.',
    isFree: false,
    requiresKey: true,
  },
  {
    id: 'gemini-3.7-flash',
    name: 'Google Gemini 3.7 Flash (Preview — 20 Req/Day)',
    provider: 'gemini',
    description: 'Next-gen experimental flash model (low 20 req/day quota limit).',
    isFree: false,
    requiresKey: true,
  },

  // 3. Groq (Ultra-Fast Free Tier)
  {
    id: 'llama-3.3-70b-versatile',
    name: 'Groq — Llama 3.3 70B (Fast & Free Key)',
    provider: 'groq',
    description: 'Sub-second response speeds using free Groq Console key (console.groq.com).',
    isFree: false,
    requiresKey: true,
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    name: 'Groq — DeepSeek R1 Distill 70B',
    provider: 'groq',
    description: 'High-speed distilled reasoning model hosted on Groq LPU hardware.',
    isFree: false,
    requiresKey: true,
  },

  // 4. OpenAI (BYOK)
  {
    id: 'gpt-4o',
    name: 'OpenAI GPT-4o',
    provider: 'openai',
    description: 'Flagship omni-model with top-tier executive writing quality.',
    isFree: false,
    requiresKey: true,
  },
  {
    id: 'gpt-4o-mini',
    name: 'OpenAI GPT-4o Mini',
    provider: 'openai',
    description: 'Affordable, fast, and highly accurate for resume formatting.',
    isFree: false,
    requiresKey: true,
  },
  {
    id: 'o3-mini',
    name: 'OpenAI o3-mini (Reasoning)',
    provider: 'openai',
    description: 'Advanced reasoning model for meticulous ATS keyword matching.',
    isFree: false,
    requiresKey: true,
  },

  // 5. Anthropic Claude (BYOK)
  {
    id: 'claude-3-7-sonnet-latest',
    name: 'Anthropic Claude 3.7 Sonnet',
    provider: 'claude',
    description: 'State-of-the-art hybrid reasoning for polished resume prose.',
    isFree: false,
    requiresKey: true,
  },
  {
    id: 'claude-3-5-sonnet-latest',
    name: 'Anthropic Claude 3.5 Sonnet',
    provider: 'claude',
    description: 'Gold-standard coding and technical narrative generator.',
    isFree: false,
    requiresKey: true,
  },

  // 6. OpenRouter (BYOK)
  {
    id: 'openrouter-free',
    name: 'OpenRouter (Multi-Model Gateway)',
    provider: 'openrouter',
    description: 'Connect to 100+ models using your OpenRouter unified key.',
    isFree: false,
    requiresKey: true,
  },

  // 7. Custom Remote Endpoint
  {
    id: 'custom-endpoint',
    name: 'Custom OpenAI-Compatible Endpoint',
    provider: 'custom',
    description: 'Private proxy, vLLM instance, or self-hosted API gateway.',
    isFree: false,
    requiresKey: false,
  },

  // 8. Bring Your Own AI (Prompt & Paste / 100% Free / No API Key)
  {
    id: 'byo-ai-manual',
    name: 'Bring Your Own AI (Prompt & Paste)',
    provider: 'manual',
    description: 'Copy calibrated prompts to ChatGPT, Claude, or Gemini Web and paste the response back.',
    isFree: true,
    requiresKey: false,
  },
];
