import React, { useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Box,
  Typography,
  Button,
  TextField,
  IconButton,
  Chip,
  Tooltip,
  Alert,
} from '@mui/material';
import CloseRoundedIcon from '@mui/icons-material/CloseRounded';
import ContentCopyRoundedIcon from '@mui/icons-material/ContentCopyRounded';
import CheckRoundedIcon from '@mui/icons-material/CheckRounded';
import AutoAwesomeRoundedIcon from '@mui/icons-material/AutoAwesomeRounded';
import { useTranslation } from 'react-i18next';
import { RADIUS_TOKENS } from '../../../theme/dimensions';

export interface ManualAiPromptModalProps {
  open: boolean;
  onClose: () => void;
  promptText: string;
  onSubmitResponse: (response: string) => void;
  onCopyPrompt?: () => void;
  isProcessing?: boolean;
  title?: string;
}

/**
 * Dumb/Presentational Modal & Bottom Sheet for pasting the AI response.
 * - Prompt was already copied to clipboard when opening this modal.
 * - Entire viewport is dedicated to pasting the response and generating the CV.
 * - Provides a subtle "Copy again" link just in case the clipboard was overwritten.
 */
export const ManualAiPromptModal: React.FC<ManualAiPromptModalProps> = ({
  open,
  onClose,
  promptText,
  onSubmitResponse,
  onCopyPrompt,
  isProcessing = false,
  title,
}) => {
  const { t } = useTranslation(['settings', 'common', 'target']);

  const [copied, setCopied] = useState(false);
  const [responseInput, setResponseInput] = useState('');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleCopyPrompt = async () => {
    try {
      await navigator.clipboard.writeText(promptText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
      onCopyPrompt?.();
    } catch {
      // Fallback if clipboard API is restricted
      const textarea = document.createElement('textarea');
      textarea.value = promptText;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
      onCopyPrompt?.();
    }
  };

  const handleProcess = () => {
    if (!responseInput.trim()) {
      setErrorMsg(t('settings:providers.invalidResponse', 'Please paste the AI response before continuing.'));
      return;
    }
    setErrorMsg(null);
    onSubmitResponse(responseInput.trim());
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      slotProps={{
        paper: {
          sx: {
            borderRadius: { xs: `${RADIUS_TOKENS.xl} ${RADIUS_TOKENS.xl} 0 0`, sm: RADIUS_TOKENS.xl },
            m: { xs: 0, sm: 2 },
            position: { xs: 'fixed', sm: 'relative' },
            bottom: { xs: 0, sm: 'auto' },
            maxHeight: { xs: '92vh', sm: '88vh' },
            width: { xs: '100%', sm: 'auto' },
            p: { xs: 1.5, sm: 2 },
            pb: { xs: 'max(calc(env(safe-area-inset-bottom, 0px) + 16px), 20px)', sm: 2.5 },
          },
        },
      }}
    >
      {/* Mobile Drag Handle Pill */}
      <Box
        sx={{
          display: { xs: 'block', sm: 'none' },
          width: 36,
          height: 4,
          borderRadius: RADIUS_TOKENS.full,
          bgcolor: 'divider',
          mx: 'auto',
          mb: 1.5,
          mt: 0.5,
        }}
      />

      <DialogTitle sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', pb: 0.5, px: { xs: 1, sm: 2 } }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
          <AutoAwesomeRoundedIcon color="primary" />
          <Typography variant="h6" sx={{ fontWeight: 700 }}>
            {title || t('settings:providers.pasteAiResponse', 'Paste AI Response')}
          </Typography>
          <Chip
            label={t('settings:providers.noKeyNeeded', '100% Free • No API Key')}
            size="small"
            color="success"
            sx={{ fontWeight: 700, height: 20, fontSize: '0.68rem' }}
          />
        </Box>
        <IconButton size="small" onClick={onClose} aria-label="close">
          <CloseRoundedIcon fontSize="small" />
        </IconButton>
      </DialogTitle>

      <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, pt: '6px !important', px: { xs: 1, sm: 2 } }}>
        {/* Subtle helper notice + fallback re-copy link */}
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 1 }}>
          <Typography variant="body2" color="text.secondary" sx={{ fontSize: '0.82rem' }}>
            {t('settings:providers.promptCopiedHelper', 'Prompt copied to clipboard. Paste the response generated by your AI below:')}
          </Typography>

          <Button
            size="small"
            variant="text"
            color="inherit"
            startIcon={copied ? <CheckRoundedIcon sx={{ fontSize: '15px !important' }} /> : <ContentCopyRoundedIcon sx={{ fontSize: '15px !important' }} />}
            onClick={handleCopyPrompt}
            sx={{
              fontSize: '0.75rem',
              textTransform: 'none',
              color: copied ? 'success.main' : 'text.secondary',
              py: 0.2,
              px: 1,
              flexShrink: 0,
            }}
          >
            {copied
              ? t('settings:providers.promptCopied', 'Copied!')
              : t('settings:providers.reCopyPrompt', 'Copy again')}
          </Button>
        </Box>

        {/* Spacious Paste Textarea */}
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1, flex: 1 }}>
          <TextField
            fullWidth
            multiline
            minRows={9}
            maxRows={16}
            placeholder={t(
              'settings:providers.pasteAiResponsePlaceholder',
              'Paste the complete response generated by ChatGPT, Claude, Gemini here...'
            )}
            value={responseInput}
            onChange={(e) => {
              setResponseInput(e.target.value);
              if (errorMsg) setErrorMsg(null);
            }}
            helperText={
              !responseInput.trim()
                ? t('settings:providers.pasteToEnablePrompt', 'Paste the AI response to continue')
                : undefined
            }
            sx={{
              '& .MuiInputBase-root': {
                fontFamily: 'monospace',
                fontSize: '0.82rem',
                lineHeight: 1.5,
                minHeight: { xs: '240px', sm: '290px' },
                alignItems: 'flex-start',
              },
            }}
          />
        </Box>

        {errorMsg && (
          <Alert severity="warning" sx={{ borderRadius: RADIUS_TOKENS.md }}>
            {errorMsg}
          </Alert>
        )}
      </DialogContent>

      <DialogActions sx={{ px: { xs: 1, sm: 2 }, pb: 1, pt: 1, justifyContent: 'space-between' }}>
        <Button variant="text" color="inherit" onClick={onClose} disabled={isProcessing}>
          {t('common:actions.cancel', 'Cancel')}
        </Button>
        <Tooltip
          title={
            !responseInput.trim()
              ? t('settings:providers.pasteToEnablePrompt', 'Paste the AI response to continue')
              : ''
          }
        >
          <span>
            <Button
              variant="contained"
              color="primary"
              startIcon={<AutoAwesomeRoundedIcon />}
              onClick={handleProcess}
              disabled={isProcessing || !responseInput.trim()}
              sx={{ fontWeight: 700, px: 3 }}
            >
              {t('settings:providers.generateCvAction', 'Generate CV')}
            </Button>
          </span>
        </Tooltip>
      </DialogActions>
    </Dialog>
  );
};
